-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.activity
(
    id uuid NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.person
(
    id uuid NOT NULL,
    schedule_id uuid,
    out_of_hours_plan_id uuid,
    CONSTRAINT person_pk PRIMARY KEY (id),
    UNIQUE (schedule_id)
);

CREATE TABLE IF NOT EXISTS public.schedule
(
    id uuid NOT NULL,
    CONSTRAINT schedule_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.schedule_activity
(
    schedule_id uuid NOT NULL,
    activity_id uuid NOT NULL,
    PRIMARY KEY (schedule_id, activity_id)
);

CREATE TABLE IF NOT EXISTS public.out_of_hours_plan
(
    id uuid,
    submitted_on timestamp with time zone,
    submitted_by uuid,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.person
    ADD FOREIGN KEY (schedule_id)
        REFERENCES public.schedule (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.schedule_activity
    ADD FOREIGN KEY (schedule_id)
        REFERENCES public.schedule (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.schedule_activity
    ADD FOREIGN KEY (activity_id)
        REFERENCES public.activity (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.out_of_hours_plan
    ADD FOREIGN KEY (id)
        REFERENCES public.person (out_of_hours_plan_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;

END;